trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.SourcesDirectory)'
      ArtifactName: 'InstallationArtifacts'
      publishLocation: 'Container'